Token=90091783785796245:0:FGLO4MyU6dMJB1q9m2BCM6jrMNVUXU
URI=wss://d1.nandbox.net:5020/nandbox/api/
DownloadServer=https://d1.nandbox.net:5020/nandbox/download/
UploadServer=https://d1.nandbox.net:5020/nandbox/upload/